# -*- coding: utf-8 -*-
"""320_Checkpoint_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1owI4vVIgnLBP03a2HCSzHjuSA6s4Cx8e

# Exploring Meteorological Influences on Solar Radiation in the Northeast United States

## Summer 2024 Data Science Project

### Group Members:
- Muhammad Ramamni
- Shrawan Gopal
- James Heiser
- Alexander Cruz

## 1. Introduction
In this project, we aim to analyze the relationship between various meteorological parameters and global horizontal radiation across three cities in the Northeast United States: Hartford, CT; Caribou, ME; and Philadelphia, PA. Specifically, our analysis is divided into four main sections:

### Heatmap of 12 Weather Variables
We examine the correlations among twelve weather variables, including: Dry Bulb Temperature, Dew Point Temperature, Relative Humidity, Atmospheric Station Pressure, Wind Direction, Wind Speed, Total Sky Cover, Opaque Sky Cover, Visibility, Ceiling Height, Precipitable Water, and Global Horizontal Radiation.

**Importance**: Visualizing the correlations among these weather variables helps us understand the complex interactions between different meteorological factors and their combined effect on solar radiation. This comprehensive analysis is crucial for optimizing solar energy production.

### Dry Bulb Temperature in January vs July
We compare the dry bulb temperature during the months of January and July to understand seasonal variations and their potential impact on global horizontal radiation.

**Importance**: Understanding seasonal variations in dry bulb temperature helps optimize solar energy systems for different times of the year. This knowledge is crucial for maximizing solar energy production and efficiency throughout the year.

### Total Sky Cover vs Global Horizontal Radiation
This section examines the relationship between total sky cover and global horizontal radiation to determine how cloud cover affects solar radiation received at the surface.

**Importance**: Analyzing the impact of sky cover on solar radiation is essential for predicting solar energy production and improving the design and placement of solar panels. This information can help in optimizing energy capture and storage systems.

### Dry Bulb Temperature vs Global Horizontal Radiation
We investigate the correlation between dry bulb temperature and global horizontal radiation, providing insights into how temperature variations influence solar radiation.

**Importance**: By understanding how dry bulb temperature correlates with solar radiation, we can develop predictive models to anticipate maintenance needs and optimize the performance of solar energy systems based on temperature variations.


## Our Primary Questions
1. What are the significant correlations among the 12 weather variables, and how do they interact with global horizontal radiation?
2. How does the dry bulb temperature vary between January and July?
3. What is the relationship between total sky cover and global horizontal radiation?
4. How does dry bulb temperature correlate with global horizontal radiation?

## Objectives
- **Analyze Seasonal Variations in Solar Energy Potential**
- **Assess the Impact of Weather on Energy Efficiency**
- **Forecast Solar Energy Production**


By addressing these questions and objectives, we aim to better understand the climatic factors influencing solar radiation, which is crucial for renewable energy applications and climate modeling. Additionally, understanding these relationships can help in improving weather forecasting models and developing strategies to mitigate the effects of climate change.

## 2. Data Curation


**Data Sources:**
Merket, Noel. 2020. "Weather Data for Buildings Energy Simulations." NREL Data Catalog. Golden, CO: National Renewable Energy Laboratory. Last updated: December 12, 2023. DOI: 10.7799/1603006.

https://data.nrel.gov/submissions/128

NE_Weather_2018.zip:
- PA_PHILADELPHIA-IAP_724080_18.epw
- CT_HARTFORD-BRADLEY-IAP_725080_18.epw
- ME_CARIBOU-MUNI-AP_727120_18.epw

**Data Description:**

- Dry Bulb Temperature: The air temperature as measured by a thermometer freely exposed to the air.

- Dew Point Temperature: The temperature at which air becomes saturated with moisture.

- Relative Humidity: The amount of moisture in the air relative to the maximum amount the air can hold at that temperature.

- Atmospheric Station Pressure: The pressure exerted by the atmosphere at a given point.

- Wind Direction: The direction from which the wind is blowing.

- Wind Speed: The speed at which the wind is blowing.

- Total Sky Cover: The fraction of the sky covered by clouds.

- Opaque Sky Cover: The fraction of the sky covered by opaque clouds.

- Visibility: The distance one can clearly see.

- Ceiling Height: The height above ground level of the lowest layer of clouds.

- Precipitable Water: The total amount of water vapor in a column of air.

- Global Horizontal Radiation: The total amount of shortwave radiation received from above by a horizontal surface.


EPW File Structure: The EPW file structure is well-documented. It includes a header section and a data section. The header contains data about the weather station and data source, and the data section contains the actual weather data. The columns for the weather data section are standardized across all EPW files. These typically include various parameters like temperature, humidity, wind speed, and radiation

More information on EPW's and Variables here:
-  https://designbuilder.co.uk/cahelp/Content/EnergyPlusWeatherFileFormat.htm#:~:text=The%20EnergyPlus%20data%20dictionary%20format,for%20alphanumeric%3B%20N%20for%20numeric

- https://bigladdersoftware.com/epx/docs/8-3/auxiliary-programs/energyplus-weather-file-epw-data-dictionary.html


**Data Transformation:**
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

# The columns based on EPW file structure
columns = [
    "Year", "Month", "Day", "Hour", "Minute", "Data Source and Uncertainty Flags",
    "Dry Bulb Temperature", "Dew Point Temperature", "Relative Humidity",
    "Atmospheric Station Pressure", "Extraterrestrial Horizontal Radiation",
    "Extraterrestrial Direct Normal Radiation", "Horizontal Infrared Radiation Intensity",
    "Global Horizontal Radiation", "Direct Normal Radiation", "Diffuse Horizontal Radiation",
    "Global Horizontal Illuminance", "Direct Normal Illuminance",
    "Diffuse Horizontal Illuminance", "Zenith Luminance", "Wind Direction", "Wind Speed",
    "Total Sky Cover", "Opaque Sky Cover", "Visibility", "Ceiling Height",
    "Present Weather Observation", "Present Weather Codes", "Precipitable Water",
    "Aerosol Optical Depth", "Snow Depth", "Days Since Last Snowfall", "Albedo",
    "Liquid Precipitation Depth", "Liquid Precipitation Quantity"
]


columns_to_drop = [
    "Data Source and Uncertainty Flags",
    "Albedo",
    "Liquid Precipitation Depth",
    "Liquid Precipitation Quantity",
    "Days Since Last Snowfall",
    "Present Weather Codes",
    "Aerosol Optical Depth",
    "Snow Depth",
    "Present Weather Observation"
]

#  EPW -> CSV
def process_epw(file_path, csv_file_path):
    df = pd.read_csv(file_path, sep=',', skiprows=8, header=None, names=columns) # Reading the file, skipping the first 8 lines
    df = df.drop(columns=columns_to_drop)
    df.to_csv(csv_file_path, index=False)

# PHILADELPHIA
file_path_1 = '/content/PA_PHILADELPHIA-IAP_724080_18.epw'
csv_file_path_1 = '/content/PA_PHILADELPHIA_2018.csv'
process_epw(file_path_1, csv_file_path_1)

# HARTFORD
file_path_2 = '/content/CT_HARTFORD-BRADLEY-IAP_725080_18.epw'
csv_file_path_2 = '/content/CT_HARTFORD_2018.csv'
process_epw(file_path_2, csv_file_path_2)

# CARIBOU
file_path_3 = '/content/ME_CARIBOU-MUNI-AP_727120_18.epw'
csv_file_path_3 = '/content/ME_CARIBOU_2018.csv'
process_epw(file_path_3, csv_file_path_3)

"""## 3. Exploratory Data Analysis



"""

# Imports
from scipy.stats import mannwhitneyu
from scipy.stats import pearsonr
from scipy.stats import chi2_contingency
import matplotlib.pyplot as plt
import seaborn as sns

ct_hartford = pd.read_csv('/content/CT_HARTFORD_2018.csv')
pa_philadelphia = pd.read_csv('/content/PA_PHILADELPHIA_2018.csv')
me_caribou = pd.read_csv('/content/ME_CARIBOU_2018.csv')

"""A **heat map** is used to identify patterns and correlations between many different variables. We will use a heat map here to identify any correlation between 11 different features and Global Horizontal Radiation, a measure of solar energy, for each of the three cities. This will provide us with a comprehensive understanding of the relationship each weather variable has with each other and how they individually impact solar energy."""

variables = ["Dry Bulb Temperature", "Dew Point Temperature", "Relative Humidity",
          "Atmospheric Station Pressure", "Wind Direction", "Wind Speed", "Total Sky Cover",
          "Opaque Sky Cover", "Visibility", "Ceiling Height", "Precipitable Water",
          "Global Horizontal Radiation"]

philly_corr = pd.DataFrame()
for v in variables:
  philly_corr[v] = pa_philadelphia[pa_philadelphia["Global Horizontal Radiation"] != 0][v]
sns.heatmap(data= philly_corr.corr(), cmap = "hot", annot= True, fmt = '.2f', annot_kws={'size': 8}, center= 0)
plt.title("Heatmap of 12 Weather Variables - Philadelphia\n")
plt.show()

hartford_corr = pd.DataFrame()
for v in variables:
  hartford_corr[v] = ct_hartford[ct_hartford["Global Horizontal Radiation"] != 0][v]
sns.heatmap(data= hartford_corr.corr(), cmap = "hot", annot= True, fmt = '.2f', annot_kws={'size': 8})
plt.title("Heatmap of 12 Weather Variables - Hartford\n")
plt.show()

caribou_corr = pd.DataFrame()
for v in variables:
  caribou_corr[v] = me_caribou[me_caribou["Global Horizontal Radiation"] != 0][v]
sns.heatmap(data= caribou_corr.corr(), cmap = "hot", annot= True, fmt = '.2f', annot_kws={'size': 8})
plt.title("Heatmap of 12 Weather Variables - Caribou\n")
plt.show()

"""**Conclusion:** We can see that Relative Humidity is consistently the most influential feature, having a moderate correlation (defined by a correlation coefficient with an absolute value between about 0.5 and 0.75) with Sky Cover, Ceiling Height, Visibility, and Global Horizontal Radiation. Relative Humidity is also the only feature that seems to have a significant impact on solar energy, as no other feature has a moderate or stronger correlation with Global Horizontal Radiation. However, Dry Bulb Temperature does appear to have some impact on Global Horizontal Radiation, with a correlation coefficent ranging from 0.32 to 0.47 between the three heat maps.

---

The **Mann-Whitney U Test** is used to determine whether there is a significant difference between the distributions of two independent samples. In this case, we are comparing the Dry Bulb Temperature between January and July for each city.

In this part, we analyze the dry bulb temperature data for various cities to understand the seasonal variations and their implications on solar energy efficiency. By comparing the dry bulb temperatures in January and July, we can assess the impact of temperature fluctuations on solar energy systems.

The following analysis involves the use of the Mann-Whitney U Test to determine if there is a significant difference between the dry bulb temperatures in January and July for each city. This will help us understand the seasonal variations and their potential impact on solar energy generation.
"""

winter = ct_hartford[ct_hartford['Month'] == 1]['Dry Bulb Temperature']
summer = ct_hartford[ct_hartford['Month'] == 7]['Dry Bulb Temperature']
print(f"Mann-Whitney U Test | HARTFORD, CONNECTICUT | P-value:", mannwhitneyu(winter, summer).pvalue)

winter = me_caribou[me_caribou['Month'] == 1]['Dry Bulb Temperature']
summer = me_caribou[me_caribou['Month'] == 7]['Dry Bulb Temperature']
print(f"Mann-Whitney U Test | CARIBOU, MAINE | P-value: ", mannwhitneyu(winter, summer).pvalue)

winter = pa_philadelphia[pa_philadelphia['Month'] == 1]['Dry Bulb Temperature']
summer = pa_philadelphia[pa_philadelphia['Month'] == 7]['Dry Bulb Temperature']
print(f"Mann-Whitney U Test | PHILADELPHIA, PENNSYLVANIA | P-value: ", mannwhitneyu(winter, summer).pvalue)

ct_hartford['City'] = 'Hartford, CT'
me_caribou['City'] = 'Caribou, ME'
pa_philadelphia['City'] = 'Philadelphia, PA'

combined_data = pd.concat([ct_hartford, me_caribou, pa_philadelphia])
combined_data = combined_data[combined_data['Month'].isin([1, 7])]

month_map = {1: 'January', 7: 'July'}
combined_data['Month_Name'] = combined_data['Month'].map(month_map)

# Line Graph
plt.figure(figsize=(12, 8))
sns.lineplot(x='Day', y='Dry Bulb Temperature', hue='City', style='Month_Name', markers=True, data=combined_data)
plt.title('Dry Bulb Temperature in January and July - Hartford, Caribou, and Philadelphia')
plt.xlabel('Day of the Month')
plt.ylabel('Dry Bulb Temperature (°C)')
plt.show()

"""**Conclusion:**
Based on the extremely low p-values from the Mann-Whitney U tests for Hartford, Caribou, and Philadelphia, we can conclude that there is a statistically significant difference in dry bulb temperatures between January and July in each location. The p-values indicate that the differences are highly unlikely to be due to random chance, confirming a distinct seasonal variation in temperatures.


In Hartford and Philadelphia, July temperatures are significantly higher than in January, reflecting expected seasonal variations, with Philadelphia generally warmer due to its southern location. Caribou, further north, experiences a more pronounced seasonal difference with colder winters, impacting energy consumption patterns and solar energy potential, as illustrated by the line plot showing distinct temperature trends across all three cities.

---

This analysis which calculates the **Pearson Correlation Coefficient** will help you compare the impact of Total Sky Cover on Global Horizontal Radiation across different locations. This analysis will tell us the fraction of the sky covered by clouds compared to the total amount of shortwave radiation received from above by a horizontal surface in 1 year based on location.
"""

# Function to perform analysis
def analyze_sky_cover_vs_radiation(data, location_name):
    sky_cover = data['Total Sky Cover']
    global_radiation = data['Global Horizontal Radiation']

    # Calculate the Pearson correlation coefficient
    corr_coef, p_value = pearsonr(sky_cover, global_radiation)

    print(f"{location_name}:")
    print(f"Pearson Correlation Coefficient: {corr_coef}")
    print(f"P-value: {p_value}\n")

    # Scatter plot with regression line
    plt.figure(figsize=(10, 6))
    sns.regplot(x=sky_cover, y=global_radiation, scatter_kws={'alpha':0.5})
    plt.title(f'Total Sky Cover vs Global Horizontal Radiation - {location_name}')
    plt.xlabel('Total Sky Cover')
    plt.ylabel('Global Horizontal Radiation')
    plt.show()

# Perform analysis for each location
analyze_sky_cover_vs_radiation(ct_hartford, 'Hartford, CT')
analyze_sky_cover_vs_radiation(me_caribou, 'Caribou, ME')
analyze_sky_cover_vs_radiation(pa_philadelphia, 'Philadelphia, PA')

"""Conclusion: All three cities exhibit a weak negative correlation between Total Sky Cover and Global Horizontal Radiation which means we will accept the null hypothesis. The strength of the correlation varies slightly among the cities, being weakest in Hartford and strongest in Caribou. Despite the weak correlations, the statistical significance in all cases suggests a consistent pattern where an increase in sky cover leads to a reduction in the amount of solar radiation received. The differences in correlation strengths may be influenced by geographic and climatic differences among the cities, affecting the way cloud cover impacts solar radiation. These conclusions help in understanding the relationship between cloud cover and solar energy potential in different locations, which is crucial for optimizing solar energy systems.

---

A **chi-squared test** is used to determine whether there is a significant association between categorical variables. It compares the observed frequencies of categorical data against the frequencies that would be expected if the variables were independent.
"""

dry_bulbp = pa_philadelphia['Dry Bulb Temperature']
global_radp = pa_philadelphia['Global Horizontal Radiation']

dry_bulb_bin = pd.qcut(dry_bulbp, q=10, duplicates='drop')
global_rad_bin = pd.qcut(global_radp, q=10, duplicates='drop')

contingency_table = pd.crosstab(dry_bulb_bin, global_rad_bin)
chi2, p_value, dof, expected = chi2_contingency(contingency_table)

print(f'Chi-square value: {chi2}')
print(f'P-value: {p_value}')
print(f'Degrees of freedom: {dof}')
print(f'Expected frequencies:\n {expected}')

plt.figure(figsize=(14, 8))
plt.scatter(dry_bulbp, global_radp, alpha=0.5, edgecolors='w', s=20)
plt.title('Dry Bulb Temperature vs Global Horizontal Radiation (Philadelphia 2018)')
plt.xlabel('Dry Bulb Temperature (°F)')
plt.ylabel('Global Horizontal Radiation (W/m^2)')
plt.grid(True)
plt.show()
plt.figure(figsize=(20,10))
plt.title

dry_bulbh = ct_hartford['Dry Bulb Temperature']
global_radh = ct_hartford['Global Horizontal Radiation']

dry_bulb_bin = pd.qcut(dry_bulbh, q=10, duplicates='drop')
global_rad_bin = pd.qcut(global_radh, q=10, duplicates='drop')

contingency_table = pd.crosstab(dry_bulb_bin, global_rad_bin)
chi2, p_value, dof, expected = chi2_contingency(contingency_table)

print(f'Chi-square value: {chi2}')
print(f'P-value: {p_value}')
print(f'Degrees of freedom: {dof}')
print(f'Expected frequencies:\n {expected}')

plt.figure(figsize=(14, 8))
plt.scatter(dry_bulbh, global_radh, alpha=0.5, edgecolors='w', s=20, c='darkorange')
plt.title('Dry Bulb Temperature vs Global Horizontal Radiation (Hartford 2018)')
plt.xlabel('Dry Bulb Temperature (°F)')
plt.ylabel('Global Horizontal Radiation (W/m^2)')
plt.grid(True)
plt.show()

dry_bulbc = me_caribou['Dry Bulb Temperature']
global_radc = me_caribou['Global Horizontal Radiation']

dry_bulb_bin = pd.qcut(dry_bulbc, q=10, duplicates='drop')
global_rad_bin = pd.qcut(global_radc, q=10, duplicates='drop')

contingency_table = pd.crosstab(dry_bulb_bin, global_rad_bin)
chi2, p_value, dof, expected = chi2_contingency(contingency_table)

print(f'Chi-square value: {chi2}')
print(f'P-value: {p_value}')
print(f'Degrees of freedom: {dof}')
print(f'Expected frequencies:\n {expected}')

plt.figure(figsize=(14, 8))
plt.scatter(dry_bulbc, global_radc, alpha=0.5, edgecolors='w', s=20, c='green')
plt.title('Dry Bulb Temperature vs Global Horizontal Radiation (Hartford 2018)')
plt.xlabel('Dry Bulb Temperature (°F)')
plt.ylabel('Global Horizontal Radiation (W/m^2)')
plt.grid(True)
plt.show()

"""**Conclusion**: All three cities have a very low p-value, showing that the relationship between Dry Bulb Temperature and Global Horizontal Radiation is statistically significant. Among the three cities, Hartford has the highest chi-square value, followed by Caribou and then Philadelphia. This suggests that the strength of the association between Dry Bulb Temperature and Global Horizontal Radiation is strongest in Hartford, then Caribou, and weakest (still very strong) in Philadelphia.

## 4. Primary Analysis

**Regression Analysis**

#### Reasoning
- **Predictive Capability**: Regression models can effectively quantify the impact of each meteorological variable on global horizontal radiation. This helps in developing accurate predictive models for solar energy production.
- **Interpretability**: Regression provides clear insights into how each weather variable influences global horizontal radiation. The coefficients from regression models indicate the strength and direction of these relationships.
- **Versatility**: Various forms of regression (linear, multiple, polynomial, etc.) can be applied based on the complexity of the relationships between the variables.

#### Application
1. **Correlation Analysis**: Using multiple regression, we can determine the significant correlations among the 12 weather variables and their combined effect on global horizontal radiation.
2. **Seasonal Variation**: By comparing regression models for different months (January vs. July), we can understand how the influence of dry bulb temperature on global horizontal radiation changes with seasons.
3. **Impact of Sky Cover**: Regression can model the relationship between total sky cover and global horizontal radiation, providing insights into how cloud cover affects solar radiation received at the surface.
4. **Temperature Influence**: Simple linear regression can help in analyzing how variations in dry bulb temperature impact global horizontal radiation, which is essential for optimizing solar energy systems.

First, we will perform Linear Regression with the first 11 weather variables analyzed in our heat map as the predictor variables (X), and Global Horizontal Radiation as the targt variable (y). In order that the position of the sun in the sky does not confound our model, we will restrict the time of day to be between 11 am and 2 pm for our analysis. Since the heat maps for each of the three cities displayed similar relationships between all the variables, we will combine the datasets into one to get a model that can be used to generalize predictions for the Northeast region.

Combining the datasets into one, restricting the dataset, and defining X and y for regression:
"""

data = pd.concat([ct_hartford, pa_philadelphia, me_caribou])

columns_to_drop = [
    "Year",
    "Month",
    "Day",
    "Hour",
    "Minute",
    "Extraterrestrial Horizontal Radiation",
    "Extraterrestrial Direct Normal Radiation",
    "Horizontal Infrared Radiation Intensity",
    "Direct Normal Radiation",
    "Diffuse Horizontal Radiation",
    "Global Horizontal Illuminance",
    "Direct Normal Illuminance",
    "Diffuse Horizontal Illuminance",
    "Zenith Luminance",
    "City"
]
indexGHR_data = data[(data["Hour"] < 11) | (data["Hour"] > 13)].index
data_new = data.drop(indexGHR_data)
data_new = data_new.drop(columns= columns_to_drop)

X_data = data_new.drop(columns= ["Global Horizontal Radiation"])
y_data = data_new["Global Horizontal Radiation"]

"""Applying linear regression:"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

X_train_data, X_test_data, y_train_data, y_test_data = train_test_split(X_data, y_data)
model_data = LinearRegression()
model_data.fit(X_train_data, y_train_data)
y_pred_data = model_data.predict(X_test_data)

print("Mean Squared Error : ", mean_squared_error(y_test_data, y_pred_data))
print("R2: ", r2_score(y_test_data, y_pred_data))

"""## 5. Visualization"""

# Imports

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

data = pd.concat([ct_hartford, pa_philadelphia, me_caribou])

january_data = data[data['Month'] == 1]
july_data = data[data['Month'] == 7]

X = data[data['Month'].isin([1, 7])][['Month']]
y = data[data['Month'].isin([1, 7])]['Dry Bulb Temperature']

X['Month'] = X['Month'].replace({1: 0, 7: 1})

# Fit the regression model
model = LinearRegression().fit(X, y)

# Predict using the model
y_pred = model.predict(X)

plt.figure(figsize=(14, 7))

sns.histplot(january_data['Dry Bulb Temperature'], kde=True, color='blue', label='January', alpha=0.6)
sns.histplot(july_data['Dry Bulb Temperature'], kde=True, color='red', label='July', alpha=0.6)
plt.title('Dry Bulb Temperature in January vs. July')
plt.xlabel('Dry Bulb Temperature')
plt.ylabel('Frequency')
plt.legend()
plt.show()


print("Regression Model Summary:")
print(f"Coefficients: {model.coef_}")
print(f"Intercept: {model.intercept_}")
print(f"MSE: {mean_squared_error(y, y_pred)}")
print(f"R²: {r2_score(y, y_pred)}")

# Visualization for Total Sky Cover vs. Global Horizontal Radiation
total_sky_cover = data['Total Sky Cover']
global_horizontal_radiation = data['Global Horizontal Radiation']

# Fit the regression model
X = total_sky_cover.values.reshape(-1, 1)
y = global_horizontal_radiation

model = LinearRegression().fit(X, y)

# Predict using the model
y_pred = model.predict(X)

plt.figure(figsize=(14, 7))

sns.histplot(total_sky_cover, kde=True, color='blue', label='Total Sky Cover', bins=50, alpha=0.6)
sns.histplot(global_horizontal_radiation, kde=True, color='red', label='Global Horizontal Radiation', bins=50, alpha=0.6)
plt.title('Total Sky Cover vs. Global Horizontal Radiation')
plt.xlabel('Values')
plt.ylabel('Frequency')
plt.xlim(0, 100)
plt.legend()
plt.show()

print("Regression Model Summary:")
print(f"Coefficients: {model.coef_}")
print(f"Intercept: {model.intercept_}")
print(f"MSE: {mean_squared_error(y, y_pred)}")
print(f"R²: {r2_score(y, y_pred)}")

# Scatter plot with regression line
plt.figure(figsize=(14, 7))
plt.scatter(total_sky_cover, global_horizontal_radiation, color='blue', alpha=0.5, label='Actual Data')
plt.plot(total_sky_cover, y_pred, color='red', label='Regression Line')
plt.title('Regression of Global Horizontal Radiation on Total Sky Cover')
plt.xlabel('Total Sky Cover')
plt.ylabel('Global Horizontal Radiation')
plt.legend()
plt.show()

"""**Results and Insights:**

## 6. Insights and Conclusions

Dry Bulb Temperature in January vs. July:
- The coefficient of approximately 28.57 indicates that the dry bulb temperature in July is, on average, about 28.57 degrees higher than in January.

-  The R² value of 0.80 suggests that 80% of the variance in temperature between January and July is explained by the model, indicating a strong relationship.

-  The intercept of -4.43 shows the estimated average temperature for January when adjusted to the zero baseline.

The model indicates a significant and positive difference in temperatures between January and July.

Conclusions
Total Sky Cover vs. Global Horizontal Radiation:

*   Coefficient: Indicates the average change in Global Horizontal Radiation for a one-unit change in Total Sky Cover.
*   Intercept: The estimated Global Horizontal Radiation when Total Sky Cover is zero.
*   MSE (Mean Squared Error): The average squared difference between the actual and predicted values.
*   R² (R-squared): The proportion of the variance in the dependent variable that is predictable from the independent variable.

Insights:

*   The coefficient value from the regression output indicates how much Global Horizontal Radiation changes on average with a one-unit increase in Total Sky Cover.
*   The R² value shows the proportion of variance in Global Horizontal Radiation explained by Total Sky Cover. A higher R² value suggests a stronger relationship.
*   The intercept provides the estimated value of Global Horizontal Radiation when Total Sky Cover is zero.
*   By interpreting these values, we can understand the relationship between Total Sky Cover and Global Horizontal Radiation and the effectiveness of our regression model.
"""